CREATE TABLE IF NOT EXISTS listings (
	id INT AUTO_INCREMENT PRIMARY KEY,
	listing_id VARCHAR(255) NOT NULL,
	title VARCHAR(255) NOT NULL,
	address VARCHAR(255),
	listing_url TEXT NOT NULL,
	availability TEXT DEFAULT NULL,
	project_year INT DEFAULT NULL,
	closest_mrt VARCHAR(255) DEFAULT NULL,
	distance_to_closest_mrt INT DEFAULT NULL,
	is_verified_listing BOOLEAN DEFAULT NULL,
	is_everyone_welcomed BOOLEAN DEFAULT NULL,
	listed_date DATE DEFAULT NULL,
	agent_name VARCHAR(255),
	agent_rating FLOAT DEFAULT NULL,
	listing_type ENUM('Buy', 'Rent') NOT NULL,
	unit_type ENUM('Room', 'Studio', '1 Bedroom', '2 Bedroom', '3 Bedroom', '4 Bedroom', '5+ Bedroom') NOT NULL,
	selling_price DECIMAL(12,2) DEFAULT NULL,
	selling_price_text VARCHAR(255) DEFAULT NULL,
	description TEXT DEFAULT NULL,
	property_type ENUM('condo', 'landed', 'HDB') DEFAULT NULL,
	property_type_text VARCHAR(255) DEFAULT NULL,
	ownership_type ENUM('freehold', 'leasehold') DEFAULT NULL,
	ownership_type_text VARCHAR(255) DEFAULT NULL,
	bedroom_count INT DEFAULT NULL,
	bathroom_count INT DEFAULT NULL,
	floor_size_sqft INT DEFAULT NULL,
	land_size_sqft INT DEFAULT NULL,
	psf_floor DECIMAL(12,2) DEFAULT NULL,
	psf_land DECIMAL(12,2) DEFAULT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL DEFAULT NULL,
	updated_fields TEXT DEFAULT NULL,
	updated_old_values TEXT DEFAULT NULL,
	UNIQUE KEY unique_listing (listing_id, listing_type, unit_type)
);